# Generated by Django 5.2.3 on 2026-05-23 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_path', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ciphertext', models.TextField()),
                ('iv', models.TextField()),
                ('salt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Encrypted Note',
                'verbose_name_plural': 'Encrypted Notes',
                'indexes': [models.Index(fields=['note_path'], name='notes_encry_note_pa_0c9dee_idx')],
            },
        ),
    ]
